### ISSUE TITLE
iOS Landscape

### ISSUE THREAD

**Issue by MedliPlays** [ConnectNowUK/hedgehog-css#3]
![test](https://user-images.githubusercontent.com/7777823/121873519-5da84380-ccfe-11eb-8a24-f29ff43094a2.png)

See screenshot - iPhone 12 Pro lanscape mode. Not sure why you'd hate yourself enough to use Landscape but hey ho 🤣

**Comment by MedliPlays** [comment]
![WIN_20210614_10_53_47_Pro](https://user-images.githubusercontent.com/7777823/121873970-d5766e00-ccfe-11eb-957c-b3df05026fda.jpg)

**Comment by mwargan** [comment]
Ahh two issues in one I think. One is the side-spaces, thats easy. The other is the re-size which causes the bottom bar not to attach to bottom -that one is more complex. Will look into it

**Comment by mwargan** [comment]
Hmm forgot about this on iOS - this isn't exactly a CSS issue; resolved via meta tag https://css-tricks.com/the-notch-and-css/.
