### ISSUE TITLE
Update Brand Logo Across All Digital Touchpoints

### ISSUE THREAD

**Issue by MedliPlays** [ConnectNowUK/hedgehog-css#30]
We want to update the logo of our website, applications, and other platforms, including social media.

- **Scope**:  
  This task covers the redesign and update of our brand logo on the main website, mobile applications, and all affiliated social media accounts.

- **Artwork Source**:  
  All necessary logo variants and design files are categorized and can be found in our [official Art GitHub repository](https://github.com/ConnectNowUK/art). Below is the directory structure:

  ### logo-lockup
    - AI
    - EPS
    - PDF
    - PNG
    - SVG
  
  ### logo-mark
    - AI
    - EPS
    - PDF
    - PNG
    - SVG
  
  ### logo-type
    - AI
    - EPS
    - PDF
    - PNG
    - SVG
  
  ### Favicon
    - ICO Type
    - PNG Type

- **Criteria for Success**:  
  Ensure each platform showcases the logo with clarity, appropriate sizing, and uniformity in style and color.

**Comment by MedliPlays** [comment]
Promoted to issue so we can comment, although this is assiged to the Hedgehog repo, this affects any frontends.

Note that at Twin3 we only have access to update your git repos. We cannot change your website(s).
- Chat frontend
- Queue frontend
- Hedgehog (if any)
- Component lib (if any)
- Issue Tracker frontend

**Comment by akr4m** [comment]
We will change to the landing website and social media platforms.

**Comment by MedliPlays** [comment]
Done as part of pending PRs for Chat Closure etc
